In [ ]:
#SCALED DOT PRODUCT
from IPython import get_ipython
from IPython.display import display
from tensorflow import matmul, cast, float32, math
from tensorflow.math import sqrt
from tensorflow.keras.layers import Layer
from tensorflow.keras.activations import softmax
import numpy as np

class DotProductAttention(Layer):
  def __init__(self, **kwargs):
    super().__init__(**kwargs)

  def call(self, queries, keys, values, *, d_k, mask=None):
    scores = matmul(queries, keys, transpose_b=True) / sqrt(cast(d_k, float32))
    if mask is not None:
      scores += -1e9 * mask
    weights = softmax(scores)
    return matmul(weights, values)

batch_size = 32
input_seq_length = 10
d_k = 64
d_v = 64

random = np.random.default_rng(seed=42)
queries = random.random((batch_size, input_seq_length, d_k))
keys = random.random((batch_size, input_seq_length, d_k))
values = random.random((batch_size, input_seq_length, d_v))
attention = DotProductAttention()
print(attention(queries, keys, values, d_k=d_k))

tf.Tensor(
[[[0.46824062 0.5564131  0.46830392 ... 0.49306852 0.4061299  0.46411484]
  [0.47598845 0.55510455 0.47800186 ... 0.49304226 0.40060428 0.4702602 ]
  [0.47095585 0.5524668  0.47349644 ... 0.49247035 0.41551554 0.4656694 ]
  ...
  [0.473594   0.5530096  0.48761848 ... 0.490785   0.40739113 0.47809464]
  [0.47385246 0.5515101  0.47469315 ... 0.48799852 0.40717867 0.47817177]
  [0.45735514 0.5545202  0.47318476 ... 0.48771787 0.41125482 0.45760006]]

 [[0.5257553  0.46964663 0.64925057 ... 0.5456276  0.62523377 0.49289626]
  [0.51869744 0.48040384 0.64571327 ... 0.53287935 0.6220018  0.50445914]
  [0.53110534 0.48170853 0.6410709  ... 0.5455302  0.6282068  0.4921141 ]
  ...
  [0.53149515 0.48453844 0.63667035 ... 0.52498525 0.6216751  0.5099271 ]
  [0.52042365 0.48426446 0.64478606 ... 0.5371342  0.6203686  0.5011124 ]
  [0.51877236 0.48158753 0.6400035  ... 0.5273335  0.62763    0.5056677 ]]

 [[0.5787959  0.49524885 0.5873417  ... 0.59600276 0.670287   0.5746271 ]
  [0.571639