In [1]:
from wordllama import WordLlama

In [2]:
# Load the default WordLlama model
wl = WordLlama.load()

In [3]:
# Calculate similarity between two sentences
similarity_score = wl.similarity("i went to the car", "i went to the pawn shop")
print(similarity_score)  # Output: 0.06641249096796882


0.06641247868537903


In [4]:
# Rank documents based on their similarity to a query
query = "i went to the car"
candidates = ["i went to the park", "i went to the shop", "i went to the truck", "i went to the vehicle"]
ranked_docs = wl.rank(query, candidates)
print(ranked_docs)
# Output:
# [
#   ('i went to the vehicle', 0.7441646856486314),
#   ('i went to the truck', 0.2832691551894259),
#   ('i went to the shop', 0.19732814982305436),
#   ('i went to the park', 0.15101404519322253)
# ]

[('i went to the vehicle', 0.7441647052764893), ('i went to the truck', 0.28326916694641113), ('i went to the shop', 0.19732816517353058), ('i went to the park', 0.151014044880867)]


In [5]:
sentence = "I like tigers"
tokens = wl.tokenize(sentence)
print("Tokens : ",tokens)

Tokens :  [Encoding(num_tokens=5, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])]


In [6]:
w1 = WordLlama.load(dim = 64)
embeddings = wl.embed(["the quick brown fox jumps over the lazy dog"])

In [7]:
embeddings

array([[ 0.12470592, -0.07770053,  0.02884188,  0.21934648,  0.18028675,
        -0.12956376, -0.04828436,  0.41509733,  0.07201316,  0.13917126,
         0.0855602 ,  0.12068315,  0.12699752,  0.11927379,  0.00974343,
        -0.564209  , -0.1578487 ,  0.03860474, -0.07334492, -0.26644066,
        -0.5641868 , -0.32762977, -0.38049594,  0.21294056,  0.08007257,
         0.16110507, -0.00196422,  0.3599271 ,  0.0900435 ,  0.17322887,
         0.29006264, -0.29262888,  0.41510564,  0.15712148, -0.02885853,
        -0.11202171,  0.06890869, -0.03536294, -0.06598455,  0.24811624,
        -0.20313574, -0.30398142,  0.07795299, -0.42450505,  0.10664229,
         0.7530911 ,  0.02276056,  0.12312213, -0.3221824 ,  0.15558554,
         0.29816782, -0.02808033, -0.05978116,  0.20450106, -0.4262626 ,
        -0.14082475,  0.22328836, -0.3291959 , -0.18767756, -0.29354027,
        -0.5189202 , -0.4972867 , -0.12053888,  0.11252386,  0.37966537,
         0.06360973,  0.01867121,  0.21732955, -0.3

In [8]:
import torch
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity


huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


In [9]:
from transformers import AutoTokenizer,AutoModel

In [10]:
# dataset we want embeddings for
data = pd.DataFrame({
    'title': [
        'Infringement of Copyright: Legal Proceedings and Remedies',
        'Harnessing Hugging Face: Revolutionizing NLP with Transformers Library',
        'Patent Breach Litigation: Analysis and Enforcement Strategies',
        'Quantum Computing Unleashed: Breaking Down Complexities',
        'Microbiome Mysteries: Unlocking Gut Health Secrets',
        'Solar Power Surge: Illuminating Renewable Energys Future'],
    'content': [
        'This document addresses the legal framework surrounding copyright violation, including statutory damages, injunctive relief, and defendant liabilities....',
        'Explore how Hugging Faces Transformers library is transforming NLP. Unmatched ease-of-use, advanced models, and community-driven innovation redefine AIs future...',
        'Detailing patent infringement cases, this brief explores judicial remedies, infringement criteria, and defense strategies in patent law...',
        'Demystifying quantum computings complexities. Insight into qubits, quantum supremacy, and its potential to revolutionize technology....',
        'Exploring the gut microbiomes impact on health. New research unveils links between bacteria diversity and disease prevention...',
        'Analyzing solar energys rapid growth. Innovations in photovoltaic technology and global impact on sustainable energy shift...']
})

In [11]:
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-distilroberta-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/paraphrase-distilroberta-base-v2')


In [12]:
data

title  \
0  Infringement of Copyright: Legal Proceedings a...   
1  Harnessing Hugging Face: Revolutionizing NLP w...   
2  Patent Breach Litigation: Analysis and Enforce...   
3  Quantum Computing Unleashed: Breaking Down Com...   
4  Microbiome Mysteries: Unlocking Gut Health Sec...   
5  Solar Power Surge: Illuminating Renewable Ener...   

                                             content  
0  This document addresses the legal framework su...  
1  Explore how Hugging Faces Transformers library...  
2  Detailing patent infringement cases, this brie...  
3  Demystifying quantum computings complexities. ...  
4  Exploring the gut microbiomes impact on health...  
5  Analyzing solar energys rapid growth. Innovati...

In [31]:
query = "intellectual property infringement"
def search(query, top_n=5):
    query_embeddings = get_embedding(tokenizer, model, [query])
    similarities = cosine_similarity(query_embeddings, sentence_embeddings)
    top_indices = np.argsort(-similarities[0])[:top_n]
    top_results = data.iloc[top_indices].reset_index(drop=True)
    top_results['similarity'] = similarities[0][top_indices]
    return top_results
results = search(query, top_n=3)
print(results)

                                               title  \
0  Infringement of Copyright: Legal Proceedings a...   
1  Patent Breach Litigation: Analysis and Enforce...   
2  Harnessing Hugging Face: Revolutionizing NLP w...   

                                             content  similarity  
0  This document addresses the legal framework su...    0.614404  
1  Detailing patent infringement cases, this brie...    0.503443  
2  Explore how Hugging Faces Transformers library...    0.100846  


In [13]:
data['content'].tolist()

['This document addresses the legal framework surrounding copyright violation, including statutory damages, injunctive relief, and defendant liabilities....',
 'Explore how Hugging Faces Transformers library is transforming NLP. Unmatched ease-of-use, advanced models, and community-driven innovation redefine AIs future...',
 'Detailing patent infringement cases, this brief explores judicial remedies, infringement criteria, and defense strategies in patent law...',
 'Demystifying quantum computings complexities. Insight into qubits, quantum supremacy, and its potential to revolutionize technology....',
 'Exploring the gut microbiomes impact on health. New research unveils links between bacteria diversity and disease prevention...',
 'Analyzing solar energys rapid growth. Innovations in photovoltaic technology and global impact on sustainable energy shift...']

In [14]:
# Print tokens
print("Tokens:")
print(tokenizer.tokenize(data['content'].tolist()[0]))

Tokens:
['This', 'Ġdocument', 'Ġaddresses', 'Ġthe', 'Ġlegal', 'Ġframework', 'Ġsurrounding', 'Ġcopyright', 'Ġviolation', ',', 'Ġincluding', 'Ġstatutory', 'Ġdamages', ',', 'Ġinj', 'un', 'ctive', 'Ġrelief', ',', 'Ġand', 'Ġdefendant', 'Ġliabilities', '....']


In [15]:
tokenizer(data['content'][0],padding=True, truncation=True, return_tensors='pt')

{'input_ids': tensor([[    0,   713,  3780,  8480,     5,  1030,  7208,  3817,  4857,  4565,
             6,   217, 17947,  8357,     6, 30272,   879, 32740,  3500,     6,
             8,  9191, 13189, 17220,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1]])}

In [16]:
#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

def get_embedding(tokenizer, model, data):

    # Tokenize sentences
    encoded_input = tokenizer(data, padding=True, truncation=True, return_tensors='pt')

    # Compute token embeddings
    with torch.no_grad():
        model_output = model(**encoded_input)

    # Perform pooling. In this case, max pooling.
    return mean_pooling(model_output, encoded_input['attention_mask'])

sentence_embeddings = get_embedding(tokenizer, model, data['content'].tolist())

In [17]:
inp = tokenizer(data['content'].tolist(), padding=True, truncation=True, return_tensors = 'pt')

In [18]:
inp

{'input_ids': tensor([[    0,   713,  3780,  8480,     5,  1030,  7208,  3817,  4857,  4565,
             6,   217, 17947,  8357,     6, 30272,   879, 32740,  3500,     6,
             8,  9191, 13189, 17220,     2,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1],
        [    0, 47526,   141, 30581,  3923, 38738, 34379,  5560,    16, 17828,
           234, 21992,     4,  1890, 38331,  5136,    12,  1116,    12,  3698,
             6,  3319,  3092,     6,     8,   435,    12,  9756,  4695, 28557,
           833,    83,  6209,   499,   734,     2],
        [    0, 43170,  8459, 11354, 26461,  1200,     6,    42,  4315, 17384,
          8252, 26552,     6, 26461,  8608,     6,     8,  1443,  4964,    11,
         11354,   488,   734,     2,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1],
        [    0,   495, 27171,   620,  4945, 17997, 44316,  1033, 31163,     4,
         28209,    88,  2677, 32131,    

In [19]:
inp['attention_mask'].shape

torch.Size([6, 36])

In [20]:
inp['attention_mask']

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
inp['attention_mask'].unsqueeze(-1)

tensor([[[1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0],
         [0]],

        [[1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
         [1],
    

In [22]:
model(**inp)[0]

tensor([[[ 0.6608,  0.2613,  0.1324,  ...,  0.2230, -0.1937, -1.0197],
         [ 0.7567, -0.1329,  0.2798,  ...,  0.6140, -0.0738, -0.6006],
         [ 1.1379, -0.1067,  0.5074,  ...,  0.9154, -0.2932, -0.5714],
         ...,
         [ 0.7455,  0.1351,  0.0986,  ..., -0.4379, -0.1910, -0.7784],
         [ 0.7455,  0.1351,  0.0986,  ..., -0.4379, -0.1910, -0.7784],
         [ 0.7455,  0.1351,  0.0986,  ..., -0.4379, -0.1910, -0.7784]],

        [[ 0.4481, -0.2292, -0.0164,  ..., -0.9682, -0.0828,  0.4914],
         [ 0.1816, -0.9634, -0.2064,  ..., -0.8710,  0.1292,  0.2587],
         [ 0.4683, -0.6586,  0.0847,  ..., -1.7381,  0.0395,  0.5056],
         ...,
         [-0.1308, -0.2025,  0.1954,  ..., -0.9853, -0.0030,  0.0478],
         [ 0.6509, -0.1785, -0.0460,  ..., -1.3034, -0.1198,  0.7096],
         [ 0.4321, -0.2406,  0.0156,  ..., -1.0764, -0.0419,  0.5278]],

        [[ 0.5260,  0.8332,  0.0692,  ..., -0.0471, -0.0541, -0.7240],
         [ 0.4097,  0.2303,  0.6268,  ..., -0

In [23]:
token_embedding_size = model(**inp)[0].size()

In [24]:
token_embedding_size

torch.Size([6, 36, 768])

In [25]:
inp['attention_mask'].unsqueeze(-1).expand(token_embedding_size).float()

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 

In [26]:
data['content']

0    This document addresses the legal framework su...
1    Explore how Hugging Faces Transformers library...
2    Detailing patent infringement cases, this brie...
3    Demystifying quantum computings complexities. ...
4    Exploring the gut microbiomes impact on health...
5    Analyzing solar energys rapid growth. Innovati...
Name: content, dtype: object

In [27]:
print("Sentence embeddings:")
print(sentence_embeddings)

Sentence embeddings:
tensor([[ 0.4828,  0.3504,  0.0829,  ...,  0.0499, -0.1595, -0.3722],
        [ 0.2384, -0.3978, -0.0407,  ..., -1.2387, -0.1273,  0.3967],
        [ 0.4384,  0.6839,  0.1998,  ..., -0.1153, -0.3081, -0.4717],
        [ 0.4972,  0.7983,  0.0944,  ..., -0.1175, -0.4632,  0.5812],
        [ 0.0112, -0.5605, -0.3236,  ..., -0.0455, -0.0269,  0.3353],
        [-0.1307, -0.1798, -0.2947,  ...,  1.0156,  0.3974, -0.4707]])


In [28]:
sentence_embeddings.shape

torch.Size([6, 768])

In [29]:
query = "intellectual property infringement"
def search(query, top_n=5):
    query_embeddings = get_embedding(tokenizer, model, [query])
    similarities = cosine_similarity(query_embeddings, sentence_embeddings)
    top_indices = np.argsort(-similarities[0])[:top_n]
    top_results = data.iloc[top_indices].reset_index(drop=True)
    top_results['similarity'] = similarities[0][top_indices]
    return top_results
results = search(query, top_n=5)
print(results)

                                               title  \
0  Infringement of Copyright: Legal Proceedings a...   
1  Patent Breach Litigation: Analysis and Enforce...   
2  Harnessing Hugging Face: Revolutionizing NLP w...   
3  Quantum Computing Unleashed: Breaking Down Com...   
4  Solar Power Surge: Illuminating Renewable Ener...   

                                             content  similarity  
0  This document addresses the legal framework su...    0.614404  
1  Detailing patent infringement cases, this brie...    0.503443  
2  Explore how Hugging Faces Transformers library...    0.100846  
3  Demystifying quantum computings complexities. ...    0.063512  
4  Analyzing solar energys rapid growth. Innovati...    0.007385  
