In [1]:
import numpy as np
import math
from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity
from nltk.tokenize import sent_tokenize,word_tokenize

In [2]:
input = open("text.txt","r")

In [3]:
#input = "The orange cat sat on the blue couch and the black dog slept on the rug. The cat did not cross the street because it was too wet."

In [4]:
s = input.read()
f = s.replace("\n", " ") 

In [5]:
f

'The black cat sat on the couch and the brown dog slept on the rug.The cat did not cross the street because it was too wet.The dog sat on the couch near the rug.The black cat sat on the couch and the brown dog slept on the rug.The cat did not cross the street because it was too wet.The dog sat on the couch near the rug. The black cat sat on the couch and the brown dog slept on the rug.The cat did not cross the street because it was too wet.The dog sat on the couch near the rug. The black cat sat on the couch and the brown dog slept on the rug.The cat did not cross the street because it was too wet.The dog sat on the couch near the rug. The black cat sat on the couch and the brown dog slept on the rug.The cat did not cross the street because it was too wet.The dog sat on the couch near the rug. The black cat sat on the couch and the brown dog slept on the rug.The cat did not cross the street because it was too wet.The dog sat on the couch near the rug. The black cat sat on the couch and

In [6]:
#f = 'The black cat sat on the couch and the brown dog slept on the rug.The cat did not cross the street because it was too wet.'

### This is the step of tokenizing the text

In [7]:
data = []
for i in sent_tokenize(f):
    temp = []
    for j in word_tokenize(i):
        temp.append(j)
    data.append(temp)
print(data)

[['The', 'black', 'cat', 'sat', 'on', 'the', 'couch', 'and', 'the', 'brown', 'dog', 'slept', 'on', 'the', 'rug.The', 'cat', 'did', 'not', 'cross', 'the', 'street', 'because', 'it', 'was', 'too', 'wet.The', 'dog', 'sat', 'on', 'the', 'couch', 'near', 'the', 'rug.The', 'black', 'cat', 'sat', 'on', 'the', 'couch', 'and', 'the', 'brown', 'dog', 'slept', 'on', 'the', 'rug.The', 'cat', 'did', 'not', 'cross', 'the', 'street', 'because', 'it', 'was', 'too', 'wet.The', 'dog', 'sat', 'on', 'the', 'couch', 'near', 'the', 'rug', '.'], ['The', 'black', 'cat', 'sat', 'on', 'the', 'couch', 'and', 'the', 'brown', 'dog', 'slept', 'on', 'the', 'rug.The', 'cat', 'did', 'not', 'cross', 'the', 'street', 'because', 'it', 'was', 'too', 'wet.The', 'dog', 'sat', 'on', 'the', 'couch', 'near', 'the', 'rug', '.'], ['The', 'black', 'cat', 'sat', 'on', 'the', 'couch', 'and', 'the', 'brown', 'dog', 'slept', 'on', 'the', 'rug.The', 'cat', 'did', 'not', 'cross', 'the', 'street', 'because', 'it', 'was', 'too', 'wet.The

In [8]:
model = Word2Vec(data,min_count=1,vector_size=512,window=5,sg = 1)

In [9]:
word1 = 'black'
word2 = 'brown'

In [10]:
pos1 = data[0].index(word1) + 1
pos2 = data[0].index(word2) + 1
print(f"Position of {word1} : ",pos1)
print(f"Position of {word2} : ",pos2)

Position of black :  2
Position of brown :  10


The below code retrieves the vector embedding of the given words based upon the preferred size

In [11]:
a = model.wv[word1]
b = model.wv[word2]

In [12]:
len(a)

512

In [13]:
a

array([-0.05441973, -0.0863547 , -0.0017514 ,  0.11042178, -0.02671809,
        0.00457652,  0.04566022, -0.01850704, -0.01792296, -0.00872043,
        0.00896509, -0.00510498,  0.01116247, -0.01365918, -0.0346489 ,
       -0.00976884,  0.05941276,  0.10502399, -0.04968107, -0.04847107,
        0.06232915, -0.01243717,  0.10425414,  0.0447627 , -0.01387237,
       -0.00634105,  0.01926252,  0.08223861,  0.00835812, -0.10834222,
       -0.04594817,  0.07841273,  0.07965474,  0.0018017 , -0.03013139,
        0.00837232,  0.09535804, -0.03900802, -0.00375742, -0.01916074,
       -0.07248831,  0.07123309, -0.06735796, -0.03755805,  0.04227541,
        0.00210774,  0.0061413 ,  0.03753241,  0.08863604,  0.11066309,
       -0.0420329 ,  0.01437524,  0.06062197,  0.11054992, -0.04825729,
       -0.02884888,  0.03413361, -0.10415655,  0.01174006,  0.06670907,
        0.06507768, -0.00791308,  0.03593346,  0.03220853, -0.01211906,
       -0.02353419, -0.02792528,  0.03638556, -0.01453721, -0.00

In [14]:
b

array([-5.51640391e-02, -8.69774222e-02, -2.55280826e-03,  1.10678732e-01,
       -2.88184471e-02,  1.62754278e-03,  4.66233566e-02, -1.58642884e-02,
       -1.76712498e-02, -9.78153571e-03,  8.77878908e-03, -6.02419348e-03,
        1.18644405e-02, -1.23421224e-02, -3.51073444e-02, -1.06958728e-02,
        5.77316284e-02,  1.06081612e-01, -5.16196638e-02, -4.80807796e-02,
        6.13686591e-02, -1.09015312e-02,  1.02812327e-01,  4.46859561e-02,
       -1.13885198e-02, -9.24560428e-03,  2.05191504e-02,  8.29336271e-02,
        9.22461879e-03, -1.08102411e-01, -4.27965261e-02,  7.98422694e-02,
        8.06094483e-02,  3.37520009e-03, -2.93049552e-02,  8.73496011e-03,
        9.51124579e-02, -3.69399823e-02, -2.65092775e-03, -2.03795899e-02,
       -7.57788569e-02,  7.33171552e-02, -6.98468834e-02, -3.78243588e-02,
        4.29353788e-02,  7.83633790e-04,  6.16876502e-03,  3.65799963e-02,
        8.90475512e-02,  1.14879340e-01, -3.93186770e-02,  1.54582029e-02,
        5.84899373e-02,  

### Next we calculate cosine similarity manually

cos(theta) = A.B/||A||||B||

In [15]:
dot_product = np.dot(a,b)
dot_product

1.4310583

In [16]:
norm_a = np.linalg.norm(a)
norm_a

1.1934086

In [17]:
norm_b = np.linalg.norm(b)
norm_b

1.1997324

In [18]:
cos = dot_product/(norm_a*norm_b)
cos

0.9995022

### Next we calculate cosine similarity using libraries just to cross verify

In [19]:
a_reshaped = a.reshape(1,512) 
b_reshaped = b.reshape(1,512)
cos_lib = cosine_similarity(a_reshaped, b_reshaped)
print(cos_lib[0])

[0.99950206]


Hence we've verified that the cosine similarity that we calculated using libraries is equal to the cosine similarity calculated manually

### Next we try to integrate sinusoidal positional encoding into the embedded word

In [20]:
pe1 = a_reshaped.copy()
pe2 = b_reshaped.copy()
paa = a_reshaped.copy()
pba = b_reshaped.copy()
d_model = 512

In [21]:
for i in range(0, 512,2):
                pe1[0][i] = math.sin(pos1 / (10000 ** ((2 * i)/d_model)))
                paa[0][i] = (paa[0][i]*math.sqrt(d_model))+ pe1[0][i]
                
                pe1[0][i+1] = math.cos(pos1 / (10000 ** ((2 * i)/d_model)))
                paa[0][i+1] = (paa[0][i+1]*math.sqrt(d_model))+pe1[0][i+1]


In [22]:
for i in range(0, 512,2):
                pe2[0][i] = math.sin(pos2 / (10000 ** ((2 * i)/d_model)))
                pba[0][i] = (pba[0][i]*math.sqrt(d_model))+ pe2[0][i]
                
                pe2[0][i+1] = math.cos(pos2 / (10000 ** ((2 * i)/d_model)))
                pba[0][i+1] = (pba[0][i+1]*math.sqrt(d_model))+pe2[0][i+1]

In [23]:
print(word1," ",word2)

black   brown


In [24]:
cos_lib = cosine_similarity(a_reshaped, b_reshaped)
print(cos_lib,"word similarity")

[[0.99950206]] word similarity


In [25]:

cos_lib = cosine_similarity(pe1, pe2)
print(cos_lib,"positional similarity")

[[0.8600013]] positional similarity


In [26]:
cos_lib = cosine_similarity(paa, pba)
print(cos_lib,"positional encoding similarity")


[[0.9639004]] positional encoding similarity


### Sentence : The black cat sat on the couch and the brown dog slept on the rug.The cat did not cross the street because it was too wet.The dog sat on the couch near the rug.

### Cosine similarity with only word embedding

In [28]:
cosine_similarity(a_reshaped,b_reshaped)

array([[0.99950206]], dtype=float32)

### Cosine similarity with positional encoding implemented

In [29]:
cosine_similarity(paa,pba)

array([[0.9639004]], dtype=float32)